In [4]:
%%time
a = [i for i in range(100000)]
b = [i for i in range(100000)]

c = []
for i in range(len(a)):
    c.append(a[i] + 2 * b[i])

CPU times: user 11.9 ms, sys: 4.13 ms, total: 16.1 ms
Wall time: 16.5 ms


In [5]:
%%time
import numpy as np

a = np.arange(100000)
b = np.arange(100000)

c = a + 2 * b

CPU times: user 1.98 ms, sys: 2.42 ms, total: 4.41 ms
Wall time: 3.45 ms


Regular python is much slower due to:
    - type-checking
    - abstractions
    - interpreting code

Numpy uses pre-compiled C code.

**Vectorization**
- Applying operation to arrays instead of just numbers.
- Representing like mathematical notation.

**ndarray**

* Same type and fixed size, hence offer less flexibility than Python lists.
* Can be much more efficient runtime and memory wise.
* Python lists are array of pointers. This indirection adds both latency and more memory.

In [1]:
import numpy as np

a = np.array([1, 2, 3])
print(a.shape)
print(type(a))

b = np.array([[1, 2, 3], 
            [4, 5, 6]])
print(b.shape)
print(type(b))

c = np.zeros((2, 2))
print(c)
d = np.full((2, 3), 7)
print(d)

(3,)
<class 'numpy.ndarray'>
(2, 3)
<class 'numpy.ndarray'>
[[0. 0.]
 [0. 0.]]
[[7 7 7]
 [7 7 7]]


In [3]:
nums = np.arange(8)
print(nums)
print(nums.shape)

nums = nums.reshape(2, 4)
print(nums)

nums = nums.reshape(4, -1)
print(nums)

print(nums.min())
print(np.min(nums))

[0 1 2 3 4 5 6 7]
(8,)
[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
0
0


In [6]:
# Array operations or math

x = np.array([
    [1, 2],
    [3, 4]
], dtype=np.float64)

y = np.array([
    [5, 6],
    [7, 8]
], dtype=np.float64)

print(x + y, x - y, x * y, np.sqrt(x))

[[ 6.  8.]
 [10. 12.]] [[-4. -4.]
 [-4. -4.]] [[ 5. 12.]
 [21. 32.]] [[1.         1.41421356]
 [1.73205081 2.        ]]


In [9]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(x))
print(np.sum(x, axis=0)) # column
print(np.sum(x, axis=1)) # row

print(np.argmax(x, axis=1))

21
[5 7 9]
[ 6 15]
[2 2]


In [12]:
x = np.array([ [[1, 2, 3], [4, 5, 6]], [[10, 23, 33], [43, 52, 16]] ])
print(x.shape)
print(x.max(axis=0))

(2, 2, 3)
[[10 23 33]
 [43 52 16]]


In [15]:
# Indexing

a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
])
print(a[0][0], a[0, 0])
print(a[:2]) # first 2 rows
print(a[:2, 1:3]) # second and third columns from first 2 rows
print(a[0, ::-1])

1 1
[[1 2 3 4]
 [5 6 7 8]]
[[2 3]
 [6 7]]
[4 3 2 1]
